apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp
  labels:
    tier: front-end
spec:
  replicas: 3
  template:
    metadata: 
      name: myapp-pod
      labels:
        tier: front-end     
    spec:
      containers:
      - name: nginx-deploymnet
        image: nginx:latest
        
  selector:
    matchLabels:
      tier: front-end       
