apiVersion: v1
kind: Pod
metadata:  
  name: nginx-pvs
  labels:
    app: nginx 
spec: 
  replicas: 3
  selector:
    matchLabels:
      name: nginx-pvs
      labels:
        app: nginx
  template:
    metadata:
      name: nginx-pvs
      labels:
        app: nginx 
    spec:      
      containers:
        - name: nginx
          image: nginx:alpine 
          volumeMounts:
          - name: nginx-pvc
            mountPath: /var/www/html
    volumes: 
    - name: nginx-pvc
      persistentVolumeClaim:
        claimName: local-pvc