apiVersion: v1
kind: Pod
metadata:  
  name: nginx 
  labels:
    name: nginx 
spec: 
  containers:
    - name: nginx
      image: nginx:alpine 
      volumeMounts:
      - name: nginx-pvc
        mountPath: /var/www/html
  volumes: 
    - name: nginx-pvc
      persistentVolumeClaim:
        claimName: local-pvc