apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql-h
  replicas: 3
  selector:
    matchLabels:
      labels:
        app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec: 
      containers: 
      - name: mysql
        image: mysql    
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-volume 
          mountPath: /var/lib/
  volumeClaimTemplates:
    - metadata:  
        name: mysql
        labels:
          app: mysql 
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: mysql
        resources:
          requests:
             storage: 500Mi                         