apiVersion: v1 
kind: StatefulSet
metadata: 
  name: mysql 
  labels:
    app: mysql
spec:
  serviceName: mysql-h
  replicas: 3
  selector:
    matchLabels: 
      name: mysql
      labels:
        app: mysql
  template:
    metadata: 
      name: mysql 
      labels:
        app: mysql
    spec:
    - containers:
        name: mysql-volume
        image: mysql ee
      ports:
      - containerPort: 3306
                       