apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql
  labels: 
    app: mysql
spec:
  serviceName: mysql-h
  accessModes: 
    - ReadWriteOnce
  storageClassName: mysql
  resources: 
    requests:
      storage: 500Mi
   