apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webserver
  labels:
    name: webserver
spec:
  replicas: 4
  template:
    metadata:
      name: webserver
      labels:
        name: webserver      
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts: 
          - name: shared-logs
            mountPath: /var/log/nginx
        - name: sidecar-container
          image: ubuntu:latest
          command:    
            [  
              "bin/bash",
              "-c",
              "while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"
            ]
          volumeMounts:
          - name: shared-logs
            mountPath: /var/log/nginx
      volumes:       
        - name: shared-logs
          emptyDir: {}
  selector:
     matchLabels:
        name: webserver
          