apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginx-deployment 
  labels: 
    app: myapp
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: myapp    
  template:
    metadata: 
      labels:
        app: myapp
    spec:
      securityContext: 
        runAsUser: 1001
      containers:
        - name: nginx
          image: nginx:latest
          ports:  
          - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /etc/httpd/conf/httpd.conf
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet: 
              port: 80
              path: /etc/httpd/conf/httpd.conf
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            httpGet: 
              port: 80
              path: /etc/httpd/conf/httpd.conf
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              memory: 256Mi
              cpu: 512M
            limits:
              memory: 256Mi
              cpu: 512M
          volumeMounts:
          - name: nginx-volume 
            mountPath: /var/www
      volumes:
      - name: nginx-volume
        hostPath: /home/sumanth/myapp               