apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nagios-deployment
  labels:  
    app: nagios-app
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: nagios-app
  template:
    metadata:
      labels:
        app: nagios-app
    spec:
      containers:
      - name: nagios-container
        image: jasonrivers/nagios
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nagios-service
  labels:
    app: nagios-app
spec:
  selector:
    app: nagios-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008   