apiVersion: v1 
kind: RepicationController
metadata:
  name: nginx-replicationcontroller
  labels:
    app: nginx-app
    type: front-end 
spec:
  replicas: 3
  selector:
    app: nginx-app
  template:
    metadata: 
      labels: 
        app: nginx-app
        type: front-end
    spec:
      containers:
      - name: nginx-container 
        image: nginx:latest    
        ports:
        - containerPort: 80      