apiVersion: v1
kind: Service
metadata:
  name: httpd-service-devops
  namespace: httpd-namespace-devops
spec:
  selector: 
    app: httpd 
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
 