apiVersion: v1
kind: Pod
metadata: 
  name: bee
  labels:
    app: myapp
spec:
  containers:
  - name: bee 
    image: nginx 
  tolerations:
  - key: spray
    value: mortein 
    effect: NoSchedule
    operator: Equal