apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: drupal
  template:
    metadata:
      name: drupal
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: drupal:8.6
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: drupal-volume
          mountPath: /var/www/html/modules
          subPath: modules 
        - name: drupal-volume
          mountPath: /var/www/html/profiles
          subPath: profiles
        - name: drupal-volume 
          mountPath: /var/www/html/sites
          subPath: sites  
        - name: drupal-volume
          mountPath: /var/www/html/themes
          subPath: themes
      initContainers:
      - name: init-sites-volume
        image: drupal:8.6 
        volumeMounts:
        - name: drupal-volume
          mountPath: /data
        command: 
          [
            "/bin/bash",
            "-c",
          ]  
        args:
          [
            "cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R"
          ]   
      volumes: 
      - name: drupal-volume 
        persistentVolumeClaim:
          claimName: drupal-pvc
          