apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath: 
    path: /drupal-data

