apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:                          
  name: mysql-pvc-claim
spec:                              
  storageClassName: standard       
  accessModes:
    - ReadWriteOnce                
  resources:
    requests: 
      storage: 250Mi 