apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec: 
  selector:
    name: gop-fileserver
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 31200
